language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      before_script: npm run build
      script: npm run test:ci
    - stage: release
      before_script: npm run build
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
