name: release
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14.16.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm build
      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

